## Introduction to Numpy

Li Liu

7/2/2019

In [1]:
import numpy as np

#### Pbm 1

In [8]:
A = np.array([[3,-1,4],[1,5,-9]])
B = np.array([[2,6,-5,3], [5,-8,9,7],[9,-3,-2,-3]])

In [9]:
np.dot(A,B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [10]:
# @ operator; wrapper around np.dot()
A@B

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

#### Pbm 2

In [212]:
A = np.array([[3,1,4], [1,5,9], [-5,3,1]])

In [217]:
-np.dot(np.dot(A,A),A)+9*(np.dot(A,A))-15*A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### Pbm 3

In [46]:
A = np.ones((7,7))
A = np.triu(A)
A

array([[1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [52]:
B = np.tril(-6*np.ones((7,7)))+5
B

array([[-1.,  5.,  5.,  5.,  5.,  5.,  5.],
       [-1., -1.,  5.,  5.,  5.,  5.,  5.],
       [-1., -1., -1.,  5.,  5.,  5.,  5.],
       [-1., -1., -1., -1.,  5.,  5.,  5.],
       [-1., -1., -1., -1., -1.,  5.,  5.],
       [-1., -1., -1., -1., -1., -1.,  5.],
       [-1., -1., -1., -1., -1., -1., -1.]])

In [54]:
(A@B@A).astype(np.int64)

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]], dtype=int64)

#### Pbm 4

In [58]:
def fun(A):
    B = A.copy()
    mask = B<0
    B[mask] = 0
    return B

In [63]:
A = np.array([[3,-1,4],[1,5,-9]])
fun(A)

array([[3, 0, 4],
       [1, 5, 0]])

#### Pbm 5

In [90]:
A = np.array([[0,2,4], [1,3,5]])
B = np.array([[3,0,0],[3,3,0],[3,3,3]])
C = np.array([[-2,0,0], [0,-2,0], [0,0,-2]])
I = np.eye(3,3)
Z = np.zeros((3,3))
Z2 = np.zeros((3,2))

In [99]:
c1 = np.vstack((np.zeros((4,3)), A, B))
c2 = np.vstack((A.T, Z2, Z2))
c3 = np.vstack((I, Z, C))

In [100]:
c1.shape

(9, 3)

In [101]:
c2.shape

(9, 2)

In [102]:
c3.shape

(9, 3)

In [103]:
np.hstack((c1,c2,c3))

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

#### Pbm 6

In [112]:
def rowstochastic(A):
    return (A.T/A.sum(axis=1)).T

In [115]:
A = np.array([[3,-1,4],[1,5,-9]])
rowstochastic(A)

array([[ 0.5       , -0.16666667,  0.66666667],
       [-0.33333333, -1.66666667,  3.        ]])

#### Pbm 7

In [233]:
grid = np.load("grid.npy")

In [234]:
grid

array([[ 8,  2, 22, 97, 38, 15,  0, 40,  0, 75,  4,  5,  7, 78, 52, 12,
        50, 77, 91,  8],
       [49, 49, 99, 40, 17, 81, 18, 57, 60, 87, 17, 40, 98, 43, 69, 48,
         4, 56, 62,  0],
       [81, 49, 31, 73, 55, 79, 14, 29, 93, 71, 40, 67, 53, 88, 30,  3,
        49, 13, 36, 65],
       [52, 70, 95, 23,  4, 60, 11, 42, 69, 24, 68, 56,  1, 32, 56, 71,
        37,  2, 36, 91],
       [22, 31, 16, 71, 51, 67, 63, 89, 41, 92, 36, 54, 22, 40, 40, 28,
        66, 33, 13, 80],
       [24, 47, 32, 60, 99,  3, 45,  2, 44, 75, 33, 53, 78, 36, 84, 20,
        35, 17, 12, 50],
       [32, 98, 81, 28, 64, 23, 67, 10, 26, 38, 40, 67, 59, 54, 70, 66,
        18, 38, 64, 70],
       [67, 26, 20, 68,  2, 62, 12, 20, 95, 63, 94, 39, 63,  8, 40, 91,
        66, 49, 94, 21],
       [24, 55, 58,  5, 66, 73, 99, 26, 97, 17, 78, 78, 96, 83, 14, 88,
        34, 89, 63, 72],
       [21, 36, 23,  9, 75,  0, 76, 44, 20, 45, 35, 14,  0, 61, 33, 97,
        34, 31, 33, 95],
       [78, 17, 53, 28, 22, 75

In [235]:
#row max
m1 = np.max(grid[:,:-3]*grid[:,1:-2]*grid[:,2:-1]*grid[:,3:])
m1

48477312

In [236]:
#column max
m2 = np.max(grid[:-3,:]*grid[1:-2,:]*grid[2:-1,:]*grid[3:,:])
m2

51267216

In [238]:
#right diagonal
#dia = np.diagonal(grid)
m3 = np.max(grid[:-3,:-3]*grid[1:-2,1:-2]*grid[2:-1,2:-1]*grid[3:,3:])
m3

40304286

In [243]:
#left diagonal
#dia = np.diagonal(grid, axis=1)
dia2 = np.diagonal(np.fliplr(grid))
#flip the matrix
grid2 = np.fliplr(grid)
m4 = np.max(grid2[:-3,:-3]*grid2[1:-2,1:-2]*grid2[2:-1,2:-1]*grid2[3:,3:])
m4

70600674

In [244]:
max(m1, m2, m3, m4)

70600674